[site]
title = "Yan Zhang"
description = "Personal website of Yan Zhang (Dioria)."
favicon = "/favicon.svg"
last_updated = "October 2026"

[author]
name = "Yan Zhang"
title = "M.S. Student in Applied Statistics"
institution = "Wuhan University"
avatar = "/bio.jpeg"

[social]
# Contact information (leave blank or delete to hide)

email = "1703642588@qq.com"
location = "Wuhan, China"
location_url = "https://www.google.com/maps/place/Wuhan"
location_details = [
  "Wuhan,",
  "Hubei, China"
]
github = "https://github.com/DioriaZhang"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "auto"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"
